import type { Metadata, Viewport } from "next";
import { ColorSchemeScript } from "@mantine/core";
import { MantineProvider } from "@mantine/core";
import { theme } from "../styles/theme";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // https://github.com/mantinedev/mantine/issues/7008
    <html lang="ko" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
        <link
          rel="stylesheet"
          as="style"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
